spring.application.name=Blood_Donation_API

spring.datasource.url=jdbc:mysql://localhost:3306/Blood_donation_management_api?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hansierandi7@gmail.com
spring.mail.password=mmirdrelaovcgfdd
spring.mail.protocol=smtp
spring.mail.smtp.auth=true
spring.mail.smtp.starttls.enable=true
spring.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=hansierandi7@gmail.com
#spring.mail.password=mmirdrelaovcgfdd
#spring.mail.protocol=smtp
#spring.mail.smtp.auth=true
#spring.mail.smtp.starttls.enable=true
#spring.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#spring.mail.properties.mail.debug=true







